### ISSUE TITLE
Choosing a library

### ISSUE THREAD

**Issue by matpiwowarski** [pink-ducks/Music-processing-program#1]
We have to choose audio library.
Any ideas? BASS, Allegro, OpenCV, PortAudio or Synthesis ToolKit? Which one?

- https://www.un4seen.com/
- https://liballeg.org/
- https://opencv.org/
- http://www.portaudio.com/
- https://github.com/thestk/stk

**Comment by paulinaurbas** [comment]
We can stay by bass. If we've got similar project, it'll be easier 👍
